from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('import/', views.restaurant_nominatim, name='restaurant_nominatim'),
    path('import/node-id/', views.add_by_node_id, name='add_by_node_id'),
    path('restaurants/', views.restaurant_index, name='restaurant_index'),
    path('list/', views.restaurantlist_index, name='restaurantlist_index'),
    path('list/create/', views.restaurantlist_create, name='restaurantlist_create'),
    path('list/<int:list_id>/', views.restaurantlist_detail, name='restaurantlist_detail'),
    path('list/<int:list_id>/edit/', views.restaurantlist_edit, name='restaurantlist_edit'),
    path('list/<int:list_id>/update/', views.restaurantlist_update, name='restaurantlist_update'),
    path('list/<int:list_id>/delete/', views.restaurantlist_delete, name='restaurantlist_delete'),
    path('list/<int:list_id>/follow/', views.toggle_list_follow, name='toggle_list_follow'),
    path('listitem/create/', views.restaurantlistitem_create, name='restaurantlistitem_create'),
    path('munchlogitem/create/', views.munchlogitem_create, name='munchlogitem_create'),
    path('listitem/<int:item_id>/move-up/', views.move_item_up, name='move_item_up'),
    path('listitem/<int:item_id>/move-down/', views.move_item_down, name='move_item_down'),
    path('listitem/<int:item_id>/delete/', views.restaurantlistitem_delete, name='restaurantlistitem_delete'),
    path('listitem/<int:item_id>/update/', views.restaurantlistitem_update, name='restaurantlistitem_update'),
    path('restaurant/<int:restaurant_id>/', views.restaurant_detail, name='restaurant_detail'),
    path('restaurant/<int:restaurant_id>/add-image/', views.restaurant_image_add, name='restaurant_image_add'),
    path('restaurant/<int:restaurant_id>/reimport/', views.restaurant_reimport, name='restaurant_reimport'),
    path('profile/<int:user_id>/', views.profile, name='profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/<int:user_id>/lists/', views.user_restaurantlist_index, name='user_restaurantlist_index'),
    path('profile/<int:user_id>/munchlog/', views.munch_log, name='munch_log'),
    path('profile/<int:user_id>/munchlog/edit/', views.munch_log_edit, name='munch_log_edit'),
    path('profile/<int:user_id>/following/', views.user_following_lists, name='user_following_lists'),
    path('list/<int:list_id>/followers/', views.list_followers, name='list_followers'),
    path('munchlogitem/<int:item_id>/delete/', views.munchlogitem_delete, name='munchlogitem_delete'),
    path('munchlogitem/<int:item_id>/update/', views.munchlogitem_update, name='munchlogitem_update'),
    path('api/restaurant/search/', views.restaurant_search_api, name='restaurant_search_api'),
]
