# Generated by Django 5.2.4 on 2025-07-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlist',
            name='blurb',
            field=models.TextField(blank=True, help_text='Description or notes about this list'),
        ),
    ]
