# Generated by Django 5.2.4 on 2025-07-20 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_restaurantlist_blurb'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Comment about this restaurant list', max_length=1000)),
                ('inserted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('restaurant_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='lists.restaurantlist')),
            ],
            options={
                'ordering': ['-inserted_at'],
                'indexes': [models.Index(fields=['restaurant_list', '-inserted_at'], name='lists_listc_restaur_308f10_idx')],
            },
        ),
    ]
