# Generated by Django 5.2.4 on 2025-07-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lists", "0002_alter_munchlogitem_options_munchlogitem_visited_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurantlist",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
