# Generated by Django 5.2.4 on 2025-07-11 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_restaurantlist_restaurantlistitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='restaurantlistitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='restaurantlistitem',
            name='notes',
        ),
    ]
