# Generated by Django 5.2.4 on 2025-07-20 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_listcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_lists', to=settings.AUTH_USER_MODEL)),
                ('restaurant_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='lists.restaurantlist')),
            ],
            options={
                'ordering': ['-followed_at'],
                'indexes': [models.Index(fields=['follower', '-followed_at'], name='lists_listf_followe_c8aebe_idx'), models.Index(fields=['restaurant_list', '-followed_at'], name='lists_listf_restaur_d6f745_idx')],
                'unique_together': {('follower', 'restaurant_list')},
            },
        ),
    ]
