# Generated by Django 5.2.4 on 2025-07-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_listfollow'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlist',
            name='is_munch_log',
            field=models.BooleanField(default=False, help_text="Designates if this is the user's special Munch Log"),
        ),
        migrations.AddConstraint(
            model_name='restaurantlist',
            constraint=models.UniqueConstraint(condition=models.Q(('is_munch_log', True)), fields=('owner', 'is_munch_log'), name='unique_munch_log_per_user'),
        ),
    ]
