# Generated by Django 5.2.4 on 2025-07-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_alter_restaurantlistitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='osm_id',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='osm_type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
