# Generated by Django 5.2.4 on 2025-07-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_restaurant_osm_id_restaurant_osm_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantlist',
            options={'ordering': ['-inserted_at']},
        ),
        migrations.AlterModelOptions(
            name='restaurantlistitem',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='restaurantlistitem',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes about this restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='osm_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='osm_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='restaurant',
            unique_together={('osm_type', 'osm_id')},
        ),
    ]
