# Generated by Django 5.2.4 on 2025-07-23 20:00

from django.db import migrations


def create_munch_logs(apps, schema_editor):
    User = apps.get_model('lists', 'User')
    RestaurantList = apps.get_model('lists', 'RestaurantList')
    
    # Create munch log for each existing user
    for user in User.objects.all():
        RestaurantList.objects.get_or_create(
            owner=user,
            is_munch_log=True,
            defaults={
                'name': f"{user.username}'s Munch Log",
                'blurb': "My personal log of restaurant visits and food adventures!"
            }
        )


def reverse_munch_logs(apps, schema_editor):
    RestaurantList = apps.get_model('lists', 'RestaurantList')
    # Remove all munch logs
    RestaurantList.objects.filter(is_munch_log=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_add_munch_log'),
    ]

    operations = [
        migrations.RunPython(create_munch_logs, reverse_munch_logs),
    ]