# Generated by Django 5.2.4 on 2025-07-18 12:01

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_alter_restaurantlist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Geographic location from Nominatim', null=True, srid=4326),
        ),
    ]
