# Generated by Django 5.2.4 on 2025-07-18 12:07

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0008_alter_restaurant_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(help_text='Geographic location from Nominatim', srid=4326),
        ),
    ]
