# Generated by Django 5.2.4 on 2025-07-18 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('lists', '0010_restaurant_image'), ('lists', '0011_remove_restaurant_image_restaurantimage'), ('lists', '0012_restaurantimage_alt_text_added_by')]

    dependencies = [
        ('lists', '0009_alter_restaurant_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Restaurant photo', upload_to='restaurants/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='lists.restaurant')),
                ('alt_text', models.CharField(blank=True, help_text='Alt text for accessibility', max_length=200)),
                ('added_by', models.ForeignKey(help_text='User who added this image', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
