# Generated by Django 5.2.4 on 2025-07-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0009_alter_restaurant_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(blank=True, help_text='Restaurant photo', null=True, upload_to='restaurants/'),
        ),
    ]
