# Generated by Django 5.2.4 on 2025-07-18 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('lists', '0012_remove_restaurantimage_caption_and_more'), ('lists', '0013_restaurantimage_added_by'), ('lists', '0014_alter_restaurantimage_added_by'), ('lists', '0015_alter_restaurantimage_added_by')]

    dependencies = [
        ('lists', '0011_remove_restaurant_image_restaurantimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantimage',
            name='caption',
        ),
        migrations.AddField(
            model_name='restaurantimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alt text for accessibility', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurantimage',
            name='added_by',
            field=models.ForeignKey(help_text='User who added this image', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
